### ISSUE TITLE
growlight 1.2.40 build error against nettle 4

### ISSUE THREAD

**Issue by ametzler** [dankamongmen/growlight#162]
Hello,
growlight 1.2.40 FTBFS against nettle 4.0 with:
```
/build/reproducible-path/growlight-1.2.40/src/sha.c: In function ‘sha1’:
/build/reproducible-path/growlight-1.2.40/src/sha.c:11:21: error: passing argument 2 of ‘nettle_sha1_digest’ makes pointer from integer without a cast [-Wint-conversion]
   11 |   sha1_digest(&ctx, SHA1_DIGEST_SIZE, dst);
      |                     ^~~~~~~~~~~~~~~~
      |                     |
      |                     int
In file included from /build/reproducible-path/growlight-1.2.40/src/sha.c:5:
/usr/include/nettle/sha1.h:75:22: note: expected ‘uint8_t *’ {aka ‘unsigned char *’} but argument is of type ‘int’
   75 |             uint8_t *digest);
      |             ~~~~~~~~~^~~~~~
/build/reproducible-path/growlight-1.2.40/src/sha.c:11:3: error: too many arguments to function ‘nettle_sha1_digest’; expected 2, have 3
   11 |   sha1_digest(&ctx, SHA1_DIGEST_SIZE, dst);
      |   ^~~~~~~~~~~
/usr/include/nettle/sha1.h:74:1: note: declared here
   74 | sha1_digest(struct sha1_ctx *ctx,
      | ^~~~~~~~~~~
make[3]: *** [CMakeFiles/growlight.dir/build.make:376: CMakeFiles/growlight.dir/src/sha.c.o] Error 1
```

**Comment by dankamongmen** [comment]
thanks for the report! looking into it now, should be an easy fix.

**Comment by dankamongmen** [comment]
yay, works with nettle 3.10 as well
